# Generated by Django 4.0.4 on 2022-05-05 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ludi_cource1_ludi_cource2_ludi_cource3_ludi_cource4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='фио')),
                ('phone', models.IntegerField(blank=True, max_length=150, null=True, verbose_name='номер телефона')),
                ('email', models.EmailField(blank=True, max_length=150, null=True, verbose_name='почта')),
                ('letter', models.TextField(blank=True, null=True, verbose_name='письма')),
                ('cource1', models.CharField(blank=True, max_length=150, null=True, verbose_name='курс')),
                ('cource2', models.CharField(blank=True, max_length=150, null=True, verbose_name='курс')),
                ('cource3', models.CharField(blank=True, max_length=150, null=True, verbose_name='курс')),
                ('cource4', models.CharField(blank=True, max_length=150, null=True, verbose_name='курс')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавление')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='ludi',
            options={'ordering': ['-created_at'], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
    ]
