# Generated by Django 4.0.4 on 2022-05-07 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_clients_alter_ludi_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавление')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновление')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True, verbose_name='имя акк')),
                ('title1', models.CharField(blank=True, max_length=20, null=True, verbose_name='имя соц-сети')),
                ('link', models.URLField(blank=True, null=True, verbose_name='ссылки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавление')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновление')),
            ],
            options={
                'verbose_name': 'Соц-сеть',
                'verbose_name_plural': 'Соц-сети',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='clients',
            options={'ordering': ['-created_at'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterField(
            model_name='clients',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='номер телефона'),
        ),
        migrations.AlterField(
            model_name='ludi',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='номер телефона'),
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('create_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.create')),
                ('title1', models.CharField(blank=True, max_length=20, null=True, verbose_name='имя соц-сети')),
                ('image', models.ImageField(upload_to='сoц-сети', verbose_name='фото соц-сети')),
            ],
            options={
                'verbose_name': 'Соц-сеть-img',
                'verbose_name_plural': 'Соц-сети-img',
                'ordering': ['-created_at'],
            },
            bases=('app.create',),
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('create_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.create')),
                ('image', models.ImageField(upload_to='Сотрудник/', verbose_name='фото работника')),
                ('f_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='ФИО')),
                ('post', models.CharField(blank=True, max_length=30, null=True, verbose_name='должность')),
                ('discription', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('contact', models.CharField(blank=True, max_length=200, null=True, verbose_name='контакт ссылка')),
                ('link1', models.ManyToManyField(to='app.link', verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['-created_at'],
            },
            bases=('app.create',),
        ),
        migrations.AddField(
            model_name='link',
            name='image',
            field=models.ManyToManyField(to='app.img', verbose_name='соц-сеть'),
        ),
    ]
