# Generated by Django 4.0.4 on 2022-05-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_img_image_alter_workers_link1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='contact',
            field=models.URLField(blank=True, null=True, verbose_name='контакт ссылка'),
        ),
    ]
