# Generated by Django 4.0.4 on 2022-05-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_workers_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='clas',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='не нужно'),
        ),
    ]
